# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US
tone_instructions: "Be concise and technical. Focus on actual bugs and security issues."
early_access: false
enable_free_tier: true

reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  auto_title_placeholder: "@coderabbitai"
  review_status: true
  collapse_walkthrough: false
  path_instructions:
    - path: "src/**/*.razor"
      instructions: |
        This is a Blazor component library following strict conventions. Do NOT flag the following as issues:

        **Code Ordering (Intentional)**
        Members are ordered exactly as: Constants → Read-only fields → Private fields → Backing fields → Private properties → Parameter properties → Public properties → Internal properties → Lifecycle methods → Dispose → Public methods → Internal methods → Private methods. Do not suggest reordering.

        **No Underscore Prefix (Intentional)**
        Private fields do NOT use underscore prefix. This is a project convention. Do not suggest adding underscores.

        **All Code in @code Block (Intentional)**
        All component logic is inside `@code { }`. We do NOT use partial classes or code-behind files (.razor.cs). Do not suggest splitting code.

        **Cascading Parameters (Intentional)**
        Cascading parameters are always private and use dedicated context record types. We never cascade parent components directly.

    - path: "src/**/*.cs"
      instructions: |
        This is a Blazor component library following strict conventions. Do NOT flag the following as issues:

        **BuildRenderTree with Hardcoded Sequence Numbers (Intentional)**
        Components with `As` or `RenderAs` properties use manual `BuildRenderTree` with hardcoded integer sequence numbers (0, 1, 2, ...). We intentionally do NOT use counter variables or `i++`. This is required for Blazor's diffing algorithm. Do not suggest using variables.

        **Sequence Number Gaps in Branches (Intentional)**
        Sequence numbers continue linearly through if/else branches without reuse. Numbers may appear to "skip" in branches - this is correct and intentional.

        **ElementReference Pattern (Intentional)**
        Components expose `public ElementReference? Element { get; private set; }` and use `IReferencableComponent` for component reference capture. This pattern is required for external ref support.

        **No Class/Style Parameters (Intentional)**
        Instead of `Class` and `Style` string parameters, we use `ClassValue` and `StyleValue` with `Func<TState, string>?` types. Do not suggest adding simple Class/Style parameters.

        **GC.SuppressFinalize Only With Destructor (Intentional)**
        `GC.SuppressFinalize(this)` is only included when the class has a destructor (`~ClassName()`). Do not suggest adding it otherwise.

        **Fire-and-Forget Async (Intentional)**
        Non-critical async work in lifecycle methods uses `_ = SyncMethod();` pattern. This is intentional to avoid blocking. Do not flag as "discarded task".

    - path: "src/**/*.ts"
      instructions: |
        **Symbol State Pattern - Module-Level Singleton (Intentional)**
        We use `Symbol.for('BlazorBaseUI.ComponentName.State')` with `window[STATE_KEY]` for MODULE-LEVEL SINGLETON state that must persist across hot reloads and component lifecycles. This is NOT per-component state.

        IMPORTANT: Do NOT suggest adding cleanup/dispose for Symbol-backed window state. The pattern is intentionally designed to persist. Deleting `window[STATE_KEY]` on component dispose would defeat the purpose of hot reload protection.

        Per-element state uses a DIFFERENT pattern: `WeakMap` keyed by element, which IS cleaned up via a `dispose(element)` function. Do not confuse these two patterns.

        **Heavy Logic in JS (Intentional)**
        Complex interactions (dragging, resizing, scroll effects, focus trapping, observers) are intentionally implemented in JavaScript, not C#, to avoid interop latency. Do not suggest moving to C#.

    - path: "src/**/*.js"
      instructions: |
        **Symbol State Pattern - Module-Level Singleton (Intentional)**
        We use `Symbol.for('BlazorBaseUI.ComponentName.State')` with `window[STATE_KEY]` for MODULE-LEVEL SINGLETON state that must persist across hot reloads and component lifecycles. This is NOT per-component state.

        IMPORTANT: Do NOT suggest adding cleanup/dispose for Symbol-backed window state. The pattern is intentionally designed to persist. Deleting `window[STATE_KEY]` on component dispose would defeat the purpose of hot reload protection.

        Per-element state uses a DIFFERENT pattern: `WeakMap` keyed by element, which IS cleaned up via a `dispose(element)` function. Do not confuse these two patterns.

  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - WIP
      - DO NOT MERGE
    drafts: false
    base_branches:
      - master

chat:
  auto_reply: true

knowledge_base:
  opt_out: false
  learnings:
    scope: auto
  issues:
    scope: auto
  jira:
    project_keys: []
  linear:
    team_keys: []
  pull_requests:
    scope: auto
