namespace BlazorBaseUI.Tests.NavigationMenu;

public class NavigationMenuPopupTests : BunitContext, INavigationMenuPopupContract
{
    public NavigationMenuPopupTests()
    {
        JSInterop.Mode = JSRuntimeMode.Loose;
        JsInteropSetup.SetupNavigationMenuModule(JSInterop);
    }

    private RenderFragment CreatePopupInRoot(
        string? defaultValue = null,
        Func<NavigationMenuPopupState, string>? classValue = null,
        IReadOnlyDictionary<string, object>? additionalAttributes = null)
    {
        return builder =>
        {
            builder.OpenComponent<NavigationMenuRoot>(0);
            var rootAttr = 1;
            if (defaultValue is not null)
                builder.AddAttribute(rootAttr++, "DefaultValue", defaultValue);
            builder.AddAttribute(rootAttr++, "ChildContent", (RenderFragment)(innerBuilder =>
            {
                innerBuilder.OpenComponent<NavigationMenuItem>(0);
                innerBuilder.AddAttribute(1, "Value", "item1");
                innerBuilder.AddAttribute(2, "ChildContent", (RenderFragment)(itemBuilder =>
                {
                    itemBuilder.OpenComponent<NavigationMenuTrigger>(0);
                    itemBuilder.AddAttribute(1, "ChildContent", (RenderFragment)(b => b.AddContent(0, "Trigger")));
                    itemBuilder.CloseComponent();
                }));
                innerBuilder.CloseComponent();

                innerBuilder.OpenComponent<NavigationMenuPositioner>(4);
                innerBuilder.AddAttribute(5, "ChildContent", (RenderFragment)(posBuilder =>
                {
                    posBuilder.OpenComponent<NavigationMenuPopup>(0);
                    var attrIndex = 1;
                    if (classValue is not null)
                        posBuilder.AddAttribute(attrIndex++, "ClassValue", classValue);
                    if (additionalAttributes is not null)
                        posBuilder.AddAttribute(attrIndex++, "AdditionalAttributes", additionalAttributes);
                    posBuilder.AddAttribute(attrIndex++, "ChildContent", (RenderFragment)(b => b.AddContent(0, "Popup content")));
                    posBuilder.CloseComponent();
                }));
                innerBuilder.CloseComponent();
            }));
            builder.CloseComponent();
        };
    }

    [Fact]
    public Task RendersNavByDefault()
    {
        var cut = Render(CreatePopupInRoot());

        // The root is also a nav, the popup is also a nav
        var navs = cut.FindAll("nav");
        navs.Count.ShouldBeGreaterThan(1);

        return Task.CompletedTask;
    }

    [Fact]
    public Task ForwardsAdditionalAttributes()
    {
        var cut = Render(CreatePopupInRoot(
            additionalAttributes: new Dictionary<string, object> { { "data-testid", "popup" } }
        ));

        var popup = cut.Find("nav[data-testid='popup']");
        popup.ShouldNotBeNull();

        return Task.CompletedTask;
    }

    [Fact]
    public Task HasAutoGeneratedId()
    {
        var cut = Render(CreatePopupInRoot());

        var popup = cut.Find("nav[tabindex='-1']");
        var id = popup.GetAttribute("id");
        id.ShouldNotBeNullOrEmpty();

        return Task.CompletedTask;
    }

    [Fact]
    public Task HasDataSide()
    {
        var cut = Render(CreatePopupInRoot());

        var popup = cut.Find("nav[tabindex='-1']");
        popup.GetAttribute("data-side").ShouldBe("bottom");

        return Task.CompletedTask;
    }

    [Fact]
    public Task HasDataAlign()
    {
        var cut = Render(CreatePopupInRoot());

        var popup = cut.Find("nav[tabindex='-1']");
        popup.GetAttribute("data-align").ShouldNotBeNull();

        return Task.CompletedTask;
    }

    [Fact]
    public Task HasTabIndexMinusOne()
    {
        var cut = Render(CreatePopupInRoot());

        var popup = cut.Find("nav[tabindex='-1']");
        popup.GetAttribute("tabindex").ShouldBe("-1");

        return Task.CompletedTask;
    }

    [Fact]
    public Task AppliesClassValue()
    {
        var cut = Render(CreatePopupInRoot(
            classValue: _ => "popup-class"
        ));

        var popup = cut.Find("nav[tabindex='-1']");
        popup.GetAttribute("class")!.ShouldContain("popup-class");

        return Task.CompletedTask;
    }

    [Fact]
    public Task RequiresContext()
    {
        var cut = Render<NavigationMenuPopup>(parameters => parameters
            .Add(p => p.ChildContent, builder => builder.AddContent(0, "Popup"))
        );

        cut.Markup.ShouldBeEmpty();

        return Task.CompletedTask;
    }
}
