namespace BlazorBaseUI.Tests.Contracts.NavigationMenu;

public interface INavigationMenuPopupContract
{
    Task RendersNavByDefault();
    Task ForwardsAdditionalAttributes();
    Task HasAutoGeneratedId();
    Task HasDataSide();
    Task HasDataAlign();
    Task HasTabIndexMinusOne();
    Task AppliesClassValue();
    Task RequiresContext();
    Task HasDataOpenWhenOpen();
    Task HasDataClosedWhenClosed();
    Task HasDataStartingStyleDuringTransition();
    Task HasDataEndingStyleDuringTransition();
    Task HasDataAnchorHiddenWhenAnchorHidden();
    Task AppliesOriginSideStyleForTopSide();
    Task AppliesRtlOriginSideStyleForInlineEnd();
}
