using BlazorBaseUI.Playwright.Tests.Components;

// xUnit v3 generates an entry point (XunitAutoGeneratedEntryPoint) for test execution.
// When running via 'dotnet test' or VSTest, args include '--server' or '--internal-msbuild-node'.
// When running via 'dotnet run' without args, xUnit's in-process runner should execute.
// Only start the web server when explicitly requested with --urls (used by BlazorTestFixture).

var isTestExecution = args.Any(arg => arg == "--server" || arg == "--internal-msbuild-node");
var isWebServer = args.Any(arg => arg.StartsWith("--urls", StringComparison.OrdinalIgnoreCase));

if (isTestExecution)
{
    // Delegate to xUnit's test platform for VSTest/dotnet test
    var result = Xunit.MicrosoftTestingPlatform.TestPlatformTestFramework
        .RunAsync(args, BlazorBaseUI.Playwright.Tests.SelfRegisteredExtensions.AddSelfRegisteredExtensions)
        .GetAwaiter().GetResult();
    return result;
}

if (!isWebServer)
{
    // Running via 'dotnet run' without --urls: use xUnit's in-process console runner
    var result = Xunit.Runner.InProc.SystemConsole.ConsoleRunner.Run(args).GetAwaiter().GetResult();
    return result;
}

// Web server mode: start the Blazor application (used by BlazorTestFixture via 'dotnet run --urls ...')
// Note: This path doesn't return a value because app.Run() blocks until shutdown
var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddSingleton(TimeProvider.System);
builder.Services.AddRazorComponents()
    .AddInteractiveServerComponents()
    .AddInteractiveWebAssemblyComponents();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseWebAssemblyDebugging();
}
else
{
    app.UseExceptionHandler("/Error", createScopeForErrors: true);
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}
app.UseStatusCodePagesWithReExecute("/not-found", createScopeForStatusCodePages: true);
app.UseHttpsRedirection();

app.UseAntiforgery();

app.MapStaticAssets();
app.MapRazorComponents<App>()
    .AddInteractiveServerRenderMode()
    .AddInteractiveWebAssemblyRenderMode()
    .AddAdditionalAssemblies(typeof(BlazorBaseUI.Playwright.Tests.Client._Imports).Assembly);

app.Run();

return 0;

// Required for WebApplicationFactory<Program>
public partial class Program { }
